#!/bin/sh
#SBATCH --job-name=QANet
#SBATCH --output=output.slurm
#SBATCH --time=10-00:00:00
#SBATCH --cpus-per-task=3
#SBATCH --mem=15000mb
#SBATCH --mail-type=END,FAIL,REQUEUE,STAGE_OUT
#SBATCH --mail-user=qhv200@nyu.edu
#SBATCH --partition=gpu
#SBATCH --nodelist=gpu6
#SBATCH --qos=h480

source activate /gpfsnyu/scratch/qhv200/conda_envs/tf1.8_py3.6

cd /gpfsnyu/scratch/qhv200/nlp/QANet

MPLBACKEND=Agg python config.py --mode prepro

